system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: http://127.0.0.1:9999/ht-store/repo
  app_repo: http://127.0.0.1:9999/ht-store/app
  is_demo: false
  is_intl: true
  port: 9999
  username: admin
  password: Ht_123456

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
